services:
  iot-peripheral:
    build:
      context: .
      dockerfile: Dockerfile.iot
    platform: linux/arm64
    network_mode: host
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
    volumes:
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped

  web-kiosk:
    build:
      context: .
      dockerfile: Dockerfile.web
    platform: linux/arm64
    network_mode: host
    restart: unless-stopped
